name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm clean
      - run: pnpm build
      - run: pnpm dlx @plasmo-corp/mystic-box test-zip 0.0.8
      - uses: plasmo-corp/soft-secret@v1
        with:
          secret: ${{ secrets.TEST_KEY }}
          target: "key.json"
      - run: pnpm test
